server:
  port: 8080
  uploadDir: "uploads"
  staticDir: "static"
  tls:
    enabled: true
    certFile: "certs/server.crt"
    keyFile: "certs/server.key"
  redirect:
    enabled: true
    httpPort: 8081
  
communication:
  # Available protocols: http
  protocol: http
  
  # Protocol-specific settings
  http:
    heartbeatInterval: 60  # seconds
    
security:
  enableCORS: true
  corsOrigins: ["*"]
  
logging:
  level: info
  file: "server.log"