[communication]
protocol = "socks5"

[communication.socks5]
port = 1080
require_auth = false
timeout = 300  # 5 minutes
# Optionally configure authentication
# username = "user"
# password = "pass"
# Configure allowed IPs (empty = all allowed)
allowed_ips = []
# Configure disallowed ports (empty = all allowed)
disallowed_ports = []