[package]
name = "agent"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
chrono = "0.4"
ureq = "2.9"
