[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
chrono = "0.4"
uuid = { version = "1.0", features = ["v4"] }
ureq = { version = "2.4", features = ["json"] }
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hostname = "0.3"
os_info = "3.7"
rand = "0.8"
